# Generated by Django 4.1.2 on 2023-01-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.IntegerField()),
                ('cantidad_personas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('fecha_solicitud', models.DateField()),
                ('fecha_reserva', models.DateField()),
                ('cantidad_personas', models.IntegerField()),
            ],
        ),
    ]
