# Generated by Django 4.1.5 on 2023-01-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0002_remove_usuario_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_reserva',
            field=models.TimeField(null=True),
        ),
    ]
