# Generated by Django 4.1.5 on 2023-01-12 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0003_usuario_hora_alter_usuario_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_reserva',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
