# Generated by Django 4.1.5 on 2023-01-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0004_alter_usuario_fecha_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cantidad_reservas',
            field=models.IntegerField(default=1),
        ),
    ]
