# Generated by Django 4.1.5 on 2023-01-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0005_usuario_cantidad_reservas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cantidad_reservas',
        ),
    ]
