# Generated by Django 4.1.5 on 2023-01-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0006_remove_usuario_cantidad_reservas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='hora',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_reserva',
            field=models.TimeField(null=True),
        ),
    ]
