# Generated by Django 4.1.5 on 2023-01-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0007_remove_usuario_hora_alter_usuario_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_reserva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
